################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_FILES += "..\BSW\mcal_base\tricore_general\ssc\src\Mcal.c"
OBJ_FILES += "BSW\mcal_base\tricore_general\ssc\src\Mcal.o"
"BSW\mcal_base\tricore_general\ssc\src\Mcal.o" : "..\BSW\mcal_base\tricore_general\ssc\src\Mcal.c" "BSW\mcal_base\tricore_general\ssc\src\.Mcal.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\tricore_general\ssc\src\.Mcal.o.opt"

"BSW\mcal_base\tricore_general\ssc\src\.Mcal.o.opt" : .refresh
	@argfile "BSW\mcal_base\tricore_general\ssc\src\.Mcal.o.opt" -o "BSW\mcal_base\tricore_general\ssc\src\Mcal.o" "..\BSW\mcal_base\tricore_general\ssc\src\Mcal.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\tricore_general\ssc\src\.Mcal.o.d" -Wc--make-target="BSW\mcal_base\tricore_general\ssc\src\Mcal.o"
DEPENDENCY_FILES += "BSW\mcal_base\tricore_general\ssc\src\.Mcal.o.d"

C_FILES += "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.c"
OBJ_FILES += "BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.o"
"BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.o" : "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.c" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_DmaLib.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\tricore_general\ssc\src\.Mcal_DmaLib.o.opt"

"BSW\mcal_base\tricore_general\ssc\src\.Mcal_DmaLib.o.opt" : .refresh
	@argfile "BSW\mcal_base\tricore_general\ssc\src\.Mcal_DmaLib.o.opt" -o "BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.o" "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\tricore_general\ssc\src\.Mcal_DmaLib.o.d" -Wc--make-target="BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.o"
DEPENDENCY_FILES += "BSW\mcal_base\tricore_general\ssc\src\.Mcal_DmaLib.o.d"

C_FILES += "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.c"
OBJ_FILES += "BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.o"
"BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.o" : "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.c" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_TcLib.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\tricore_general\ssc\src\.Mcal_TcLib.o.opt"

"BSW\mcal_base\tricore_general\ssc\src\.Mcal_TcLib.o.opt" : .refresh
	@argfile "BSW\mcal_base\tricore_general\ssc\src\.Mcal_TcLib.o.opt" -o "BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.o" "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\tricore_general\ssc\src\.Mcal_TcLib.o.d" -Wc--make-target="BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.o"
DEPENDENCY_FILES += "BSW\mcal_base\tricore_general\ssc\src\.Mcal_TcLib.o.d"

C_FILES += "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.c"
OBJ_FILES += "BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.o"
"BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.o" : "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.c" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_WdgLib.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\tricore_general\ssc\src\.Mcal_WdgLib.o.opt"

"BSW\mcal_base\tricore_general\ssc\src\.Mcal_WdgLib.o.opt" : .refresh
	@argfile "BSW\mcal_base\tricore_general\ssc\src\.Mcal_WdgLib.o.opt" -o "BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.o" "..\BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\tricore_general\ssc\src\.Mcal_WdgLib.o.d" -Wc--make-target="BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.o"
DEPENDENCY_FILES += "BSW\mcal_base\tricore_general\ssc\src\.Mcal_WdgLib.o.d"


GENERATED_FILES += "BSW\mcal_base\tricore_general\ssc\src\Mcal.o" "BSW\mcal_base\tricore_general\ssc\src\.Mcal.o.opt" "BSW\mcal_base\tricore_general\ssc\src\.Mcal.o.d" "BSW\mcal_base\tricore_general\ssc\src\Mcal.src" "BSW\mcal_base\tricore_general\ssc\src\Mcal.lst" "BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.o" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_DmaLib.o.opt" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_DmaLib.o.d" "BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.src" "BSW\mcal_base\tricore_general\ssc\src\Mcal_DmaLib.lst" "BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.o" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_TcLib.o.opt" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_TcLib.o.d" "BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.src" "BSW\mcal_base\tricore_general\ssc\src\Mcal_TcLib.lst" "BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.o" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_WdgLib.o.opt" "BSW\mcal_base\tricore_general\ssc\src\.Mcal_WdgLib.o.d" "BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.src" "BSW\mcal_base\tricore_general\ssc\src\Mcal_WdgLib.lst"
