################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_FILES += "..\BSW\mcal_base\integration_general\src\CanIf.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\CanIf.o"
"BSW\mcal_base\integration_general\src\CanIf.o" : "..\BSW\mcal_base\integration_general\src\CanIf.c" "BSW\mcal_base\integration_general\src\.CanIf.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.CanIf.o.opt"

"BSW\mcal_base\integration_general\src\.CanIf.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.CanIf.o.opt" -o "BSW\mcal_base\integration_general\src\CanIf.o" "..\BSW\mcal_base\integration_general\src\CanIf.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.CanIf.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\CanIf.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.CanIf.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\CanIf_Cbk.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\CanIf_Cbk.o"
"BSW\mcal_base\integration_general\src\CanIf_Cbk.o" : "..\BSW\mcal_base\integration_general\src\CanIf_Cbk.c" "BSW\mcal_base\integration_general\src\.CanIf_Cbk.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.CanIf_Cbk.o.opt"

"BSW\mcal_base\integration_general\src\.CanIf_Cbk.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.CanIf_Cbk.o.opt" -o "BSW\mcal_base\integration_general\src\CanIf_Cbk.o" "..\BSW\mcal_base\integration_general\src\CanIf_Cbk.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.CanIf_Cbk.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\CanIf_Cbk.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.CanIf_Cbk.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\Dem.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\Dem.o"
"BSW\mcal_base\integration_general\src\Dem.o" : "..\BSW\mcal_base\integration_general\src\Dem.c" "BSW\mcal_base\integration_general\src\.Dem.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.Dem.o.opt"

"BSW\mcal_base\integration_general\src\.Dem.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.Dem.o.opt" -o "BSW\mcal_base\integration_general\src\Dem.o" "..\BSW\mcal_base\integration_general\src\Dem.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.Dem.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\Dem.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.Dem.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\Det.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\Det.o"
"BSW\mcal_base\integration_general\src\Det.o" : "..\BSW\mcal_base\integration_general\src\Det.c" "BSW\mcal_base\integration_general\src\.Det.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.Det.o.opt"

"BSW\mcal_base\integration_general\src\.Det.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.Det.o.opt" -o "BSW\mcal_base\integration_general\src\Det.o" "..\BSW\mcal_base\integration_general\src\Det.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.Det.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\Det.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.Det.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\Os.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\Os.o"
"BSW\mcal_base\integration_general\src\Os.o" : "..\BSW\mcal_base\integration_general\src\Os.c" "BSW\mcal_base\integration_general\src\.Os.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.Os.o.opt"

"BSW\mcal_base\integration_general\src\.Os.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.Os.o.opt" -o "BSW\mcal_base\integration_general\src\Os.o" "..\BSW\mcal_base\integration_general\src\Os.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.Os.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\Os.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.Os.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\SafetyReport.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\SafetyReport.o"
"BSW\mcal_base\integration_general\src\SafetyReport.o" : "..\BSW\mcal_base\integration_general\src\SafetyReport.c" "BSW\mcal_base\integration_general\src\.SafetyReport.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.SafetyReport.o.opt"

"BSW\mcal_base\integration_general\src\.SafetyReport.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.SafetyReport.o.opt" -o "BSW\mcal_base\integration_general\src\SafetyReport.o" "..\BSW\mcal_base\integration_general\src\SafetyReport.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.SafetyReport.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\SafetyReport.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.SafetyReport.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\SchM.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\SchM.o"
"BSW\mcal_base\integration_general\src\SchM.o" : "..\BSW\mcal_base\integration_general\src\SchM.c" "BSW\mcal_base\integration_general\src\.SchM.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.SchM.o.opt"

"BSW\mcal_base\integration_general\src\.SchM.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.SchM.o.opt" -o "BSW\mcal_base\integration_general\src\SchM.o" "..\BSW\mcal_base\integration_general\src\SchM.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.SchM.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\SchM.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.SchM.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\Test_Print.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\Test_Print.o"
"BSW\mcal_base\integration_general\src\Test_Print.o" : "..\BSW\mcal_base\integration_general\src\Test_Print.c" "BSW\mcal_base\integration_general\src\.Test_Print.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.Test_Print.o.opt"

"BSW\mcal_base\integration_general\src\.Test_Print.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.Test_Print.o.opt" -o "BSW\mcal_base\integration_general\src\Test_Print.o" "..\BSW\mcal_base\integration_general\src\Test_Print.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.Test_Print.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\Test_Print.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.Test_Print.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\Test_Setup.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\Test_Setup.o"
"BSW\mcal_base\integration_general\src\Test_Setup.o" : "..\BSW\mcal_base\integration_general\src\Test_Setup.c" "BSW\mcal_base\integration_general\src\.Test_Setup.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.Test_Setup.o.opt"

"BSW\mcal_base\integration_general\src\.Test_Setup.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.Test_Setup.o.opt" -o "BSW\mcal_base\integration_general\src\Test_Setup.o" "..\BSW\mcal_base\integration_general\src\Test_Setup.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.Test_Setup.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\Test_Setup.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.Test_Setup.o.d"

C_FILES += "..\BSW\mcal_base\integration_general\src\Test_Time.c"
OBJ_FILES += "BSW\mcal_base\integration_general\src\Test_Time.o"
"BSW\mcal_base\integration_general\src\Test_Time.o" : "..\BSW\mcal_base\integration_general\src\Test_Time.c" "BSW\mcal_base\integration_general\src\.Test_Time.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\integration_general\src\.Test_Time.o.opt"

"BSW\mcal_base\integration_general\src\.Test_Time.o.opt" : .refresh
	@argfile "BSW\mcal_base\integration_general\src\.Test_Time.o.opt" -o "BSW\mcal_base\integration_general\src\Test_Time.o" "..\BSW\mcal_base\integration_general\src\Test_Time.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\integration_general\src\.Test_Time.o.d" -Wc--make-target="BSW\mcal_base\integration_general\src\Test_Time.o"
DEPENDENCY_FILES += "BSW\mcal_base\integration_general\src\.Test_Time.o.d"


GENERATED_FILES += "BSW\mcal_base\integration_general\src\CanIf.o" "BSW\mcal_base\integration_general\src\.CanIf.o.opt" "BSW\mcal_base\integration_general\src\.CanIf.o.d" "BSW\mcal_base\integration_general\src\CanIf.src" "BSW\mcal_base\integration_general\src\CanIf.lst" "BSW\mcal_base\integration_general\src\CanIf_Cbk.o" "BSW\mcal_base\integration_general\src\.CanIf_Cbk.o.opt" "BSW\mcal_base\integration_general\src\.CanIf_Cbk.o.d" "BSW\mcal_base\integration_general\src\CanIf_Cbk.src" "BSW\mcal_base\integration_general\src\CanIf_Cbk.lst" "BSW\mcal_base\integration_general\src\Dem.o" "BSW\mcal_base\integration_general\src\.Dem.o.opt" "BSW\mcal_base\integration_general\src\.Dem.o.d" "BSW\mcal_base\integration_general\src\Dem.src" "BSW\mcal_base\integration_general\src\Dem.lst" "BSW\mcal_base\integration_general\src\Det.o" "BSW\mcal_base\integration_general\src\.Det.o.opt" "BSW\mcal_base\integration_general\src\.Det.o.d" "BSW\mcal_base\integration_general\src\Det.src" "BSW\mcal_base\integration_general\src\Det.lst" "BSW\mcal_base\integration_general\src\Os.o" "BSW\mcal_base\integration_general\src\.Os.o.opt" "BSW\mcal_base\integration_general\src\.Os.o.d" "BSW\mcal_base\integration_general\src\Os.src" "BSW\mcal_base\integration_general\src\Os.lst" "BSW\mcal_base\integration_general\src\SafetyReport.o" "BSW\mcal_base\integration_general\src\.SafetyReport.o.opt" "BSW\mcal_base\integration_general\src\.SafetyReport.o.d" "BSW\mcal_base\integration_general\src\SafetyReport.src" "BSW\mcal_base\integration_general\src\SafetyReport.lst" "BSW\mcal_base\integration_general\src\SchM.o" "BSW\mcal_base\integration_general\src\.SchM.o.opt" "BSW\mcal_base\integration_general\src\.SchM.o.d" "BSW\mcal_base\integration_general\src\SchM.src" "BSW\mcal_base\integration_general\src\SchM.lst" "BSW\mcal_base\integration_general\src\Test_Print.o" "BSW\mcal_base\integration_general\src\.Test_Print.o.opt" "BSW\mcal_base\integration_general\src\.Test_Print.o.d" "BSW\mcal_base\integration_general\src\Test_Print.src" "BSW\mcal_base\integration_general\src\Test_Print.lst" "BSW\mcal_base\integration_general\src\Test_Setup.o" "BSW\mcal_base\integration_general\src\.Test_Setup.o.opt" "BSW\mcal_base\integration_general\src\.Test_Setup.o.d" "BSW\mcal_base\integration_general\src\Test_Setup.src" "BSW\mcal_base\integration_general\src\Test_Setup.lst" "BSW\mcal_base\integration_general\src\Test_Time.o" "BSW\mcal_base\integration_general\src\.Test_Time.o.opt" "BSW\mcal_base\integration_general\src\.Test_Time.o.d" "BSW\mcal_base\integration_general\src\Test_Time.src" "BSW\mcal_base\integration_general\src\Test_Time.lst"
