################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_FILES += "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.c"
OBJ_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.o"
"BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.o" : "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.c" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm.o.opt"

"BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm.o.opt" : .refresh
	@argfile "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm.o.opt" -o "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.o" "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm.o.d" -Wc--make-target="BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.o"
DEPENDENCY_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm.o.d"

C_FILES += "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.c"
OBJ_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.o"
"BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.o" : "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.c" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm_Platform.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm_Platform.o.opt"

"BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm_Platform.o.opt" : .refresh
	@argfile "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm_Platform.o.opt" -o "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.o" "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm_Platform.o.d" -Wc--make-target="BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.o"
DEPENDENCY_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm_Platform.o.d"

C_FILES += "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.c"
OBJ_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.o"
"BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.o" : "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.c" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu.o.opt"

"BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu.o.opt" : .refresh
	@argfile "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu.o.opt" -o "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.o" "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu.o.d" -Wc--make-target="BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.o"
DEPENDENCY_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu.o.d"

C_FILES += "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.c"
OBJ_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.o"
"BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.o" : "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.c" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Crc.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Crc.o.opt"

"BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Crc.o.opt" : .refresh
	@argfile "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Crc.o.opt" -o "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.o" "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Crc.o.d" -Wc--make-target="BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.o"
DEPENDENCY_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Crc.o.d"

C_FILES += "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.c"
OBJ_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.o"
"BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.o" : "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.c" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Dma.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Dma.o.opt"

"BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Dma.o.opt" : .refresh
	@argfile "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Dma.o.opt" -o "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.o" "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Dma.o.d" -Wc--make-target="BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.o"
DEPENDENCY_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Dma.o.d"

C_FILES += "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.c"
OBJ_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.o"
"BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.o" : "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.c" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Platform.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Platform.o.opt"

"BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Platform.o.opt" : .refresh
	@argfile "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Platform.o.opt" -o "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.o" "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Platform.o.d" -Wc--make-target="BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.o"
DEPENDENCY_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Platform.o.d"

C_FILES += "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.c"
OBJ_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.o"
"BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.o" : "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.c" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Ver.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Ver.o.opt"

"BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Ver.o.opt" : .refresh
	@argfile "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Ver.o.opt" -o "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.o" "..\BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.c" -Ctc27x --lsl-core=vtc -t -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL" -Wa-H"sfr/regtc27x.def" -Wa-gAHLs --emit-locals=-equ,-symbols -Wa-Ogs -Wa--error-limit=42 -D_TASKING_C_TRICORE_ -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\ASW" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\ecum_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\compiler" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\general\tricore\inc\TC27xC" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\integration_general\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\irq_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\mcu_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\port_infineon_tricore\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_base\tricore_general\ssc\inc" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\Demo_Aurix" -I"C:\Workspace_AURIX\DEVICECONTROL_MCAL\BSW\mcal_gen\inc" --iso=90 --language=+comments,-gcc,-volatile,+strings --uchar --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O0 --tradeoff=4 -g --source -c --dep-file="BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Ver.o.d" -Wc--make-target="BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.o"
DEPENDENCY_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Ver.o.d"


GENERATED_FILES += "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.o" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm.o.opt" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm.o.d" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.src" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm.lst" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.o" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm_Platform.o.opt" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Gtm_Platform.o.d" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.src" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Gtm_Platform.lst" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.o" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu.o.opt" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu.o.d" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.src" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu.lst" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.o" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Crc.o.opt" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Crc.o.d" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.src" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Crc.lst" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.o" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Dma.o.opt" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Dma.o.d" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.src" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Dma.lst" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.o" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Platform.o.opt" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Platform.o.d" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.src" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Platform.lst" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.o" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Ver.o.opt" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\.Mcu_Ver.o.d" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.src" "BSW\mcal_base\mcu_infineon_tricore\ssc\src\Mcu_Ver.lst"
